[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 3
  
#[[main]]
#  identifier = "presentation"
#  name = "Pt"
#  url = "presentation"
#  weight = 3

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"

#[[main]]
#  identifier = "showcase"
#  name = "Showcase"
#  url = "showcase"
#  weight = 6

#[[main]]
#  identifier = "publication"
#  name = "Pub"
#  url = "publication"
#  weight = 7

[[main]]
  identifier = "weather"
  name = "Weather"
  url = "http://cepeda.qui.guifi.net/weewx/index.html"
  weight = 8